feat: kakao 연결하기
YAPP-Github/22nd-iOS-Team-1-BE pull request #105
Opened 2023-07-10 16:19 UTC by seungwooKim99

## AS-IS
- 인증 제공자 연결하기 부재(로그인/회원가입 기능만 존재)
## TO-BE
- 인증 제공자 연결을 위한 validation 진행(다음 두 조건)
  - 연결을 요청한 인증 제공자 Type이 ANONYMOUS 아님
  - 로그인한 계정과 연결된 인증 제공자 중, 연결을 요청한 인증 제공자 Type이 동일하며 ACTIVE한 인증 제공자가 없음
- 카카오 계정 연동
---
## Test
Coffice 회원 state machine의 각 상태에 따른 테스트 진행(APPLE 제외)

2023-07-11 03:29 UTC, junhaesung requested changes
고생하셨습니다- 

다음 케이스일때도 잘 동작하는지 확인 부탁드려요. 코드에서는 검증 안하는걸로 보여서요
```
coffice 1번 회원과 kakao 1번 회원이 연결된 상태에서, 
coffice 2번 회원이 kakao 1번 계정으로 연결하기 시도하는 경우
`이미 다른 계정에 연결되어있어요` 등의 메시지 주면서 실패해야함
```

2023-07-11 03:29 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberCommandServiceImpl.java
> +    public Member connectAuthProvider(Long memberId, AuthProviderCreateVo authProviderCreateVo) {
실제 비즈니스 로직(유효성 검증 등)은 도메인 서비스에서 처리해주세요 (ex, validateAuthProviderConnectRequest)

application 은 facade layer 로 다른 컴포넌트 기능을 조합하거나 위임하는 정도로만 사용해주세요. 
ApplicationService 는 트랜잭션 잡혀있지 않아서, 검사하고나서 다음 처리 하는동안 다른 스레드가 이미 처리했을 수도 있어서요

2023-07-11 03:29 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberCommandServiceImpl.java
> +        Member member = memberQueryService.getMember(memberId);
되도록 같은 계층에서 의존관계 안가지면 좋겠어요
queryService 쓰기보다  memberRepository 써주세요

2023-07-11 03:29 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberCommandService.java
> +    Member connectAuthProvider(Long memberId, AuthProviderCreateVo authProviderCreateVo);
문서에서도 `연결하기`라고 부르고 있으니 `connect` 라고만 써도 좋을거같아요

2023-07-11 03:29 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
> +    public ApiResponse<LoginResponse> connectAuthProvider(
주석에는 응답이 회원정보라고 써있는데, 클래스는 LoginResponse 쓰는 이유가 있을까요? 
연결하기 응답으로 accessToken 을 null 로 채우면서 같은 클래스를 써야할 필요성이 없어보이는데요. 
회원정보만 담는다면 MemberResponse 로 바꿔주세요

2023-07-11 03:29 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
> +    @PostMapping("/auth-providers")
`/api/v1/members/connect` 등의 path 는 어떨까요? 
팀에서 공식적으로 사용하려고 개념정리 및 용어정의 했으니, api path 나 코드 다른부분 네이밍에도 적용하면 좋을거같아요

2023-07-11 14:39 UTC, seungwooKim99 commented
말씀해주신 테스트 케이스까지 동작 확인했습니다

2023-07-12 11:04 UTC, junhaesung requested changes

2023-07-12 11:04 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberQueryServiceImpl.java
> +    public void validate(AuthProviderCreateVo authProviderCreateVo) {
멤버 연결하기 위해서 검사하는 로직이라 검증/연결이 atomic 하게 동작해야합니다. 
읽기/쓰기 트랜잭션을 나누지말고 실제 connect 동작과 한 트랜잭션으로 묶어주세요. 지금 코드도 검증, 연결 각각 트랜잭션 나눠서 쓰고있어요. 

이 코드 MemberCommandServiceImpl 로 옮기고, connect 안에서 호출하게끔 변경하면 좋을거같아요
우선 클래스 내에서만 사용할테니 인터페이스에 노출할 필요 없이 접근제어자도 private 으로 변경해주세요

2023-07-12 11:04 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberAssembler.java
>                          .map(AuthProviderResponse::of)
이번 수정범위는 아닌데, 응답 관련해서 보다가 적습니다
`authProviderUserId` 는 불필요한 정보 노출이라 응답 DTO 에서 빼주세요. 
특히 회원정보 쪽은 응답 설계하실 때 신경써주세요

2023-07-13 13:23 UTC, junhaesung approved these changes

2023-07-13 13:23 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberCommandServiceImpl.java
> +            throw new BadRequestException("이미 인증 제공자가 연결되어 있습니다. member: " + member);
에러메시지 외부로 노출될 수도 있어서, member 정보 다찍기 보다는 식별가능한 최소한의 정보만 남겨주세요 (memberId 등)

2023-07-14 00:08 UTC, merged