feat: 익명 로그인 구현 및 토큰 발급
YAPP-Github/22nd-iOS-Team-1-BE pull request #83
Opened 2023-06-28 08:09 UTC by seungwooKim99

- [x] Member, AuthProvider entity 1:N 으로 분리
- [x] 익명 로그인 구현 (/login)
- [x] JWT 발급 및 decode 추가
- [ ] 현재 로그인한 AuthProvider 정보를 Token에 담아야 함
- [ ] /me 응답 수정 필요 (이전 response와 불일치)

2023-06-28 13:40 UTC, junhaesung requested changes
고생하셨습니다! 
모양새를 갖춘 첫 PR 이고 첫 리뷰이다보니 코멘트가 좀 많아졌는데 천천히 확인해주세요- 
코드에 적기 애매한 것들 몇 개 추가합니다. 

- 빌드 실패하는데 확인해주세요
- 단위작업 마치고 머지 및 배포 가능한 상태인 코드로 PR 및 리뷰 요청해주세요. 그렇다고 완벽한 코드를 작성하라는게 아니고요, 최소한 작성자 수준에서는 테스트 완료하고, '이정도면 서비스에 배포해도 된다'는 정도의 코드라는 의미입니다. 
- 로그인한 AuthProvider 정보를 Token에 담아야 하는 이유가 있을까요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/build.gradle
> +    implementation 'com.auth0:java-jwt:4.4.0'
라이브러리 버전 등의 매직넘버는 상수로 정의해주세요 
gradle.properties 파일 및 다른 라이브러리 사용하는 코드 참고해서 수정해주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +        Date now = new Date();
Date 클래스를 사용하신 이유가 있을까요? 
java8 이상의 버전에서는 Date, Calendar 클래스 사용을 지양하고, LocalDateTime 등의 새로 추가된 시간 자료형 사용해주시는게 좋을 것 같습니다.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +    @Value("${jwt.secret}")
커스텀하게 정의하는 변수 이름은 prefix 를 추가해주세요. (ex, coffice.jwt.secret 등)
jwt 같은 범용적인 이름은 다른 라이브러리와 충돌할 가능성이 있어서요.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +    private final long INFINITE_EXPIRATION = 1000L * 60L * 60L * 24L * 365L * 100L; // 100년
기간을 나타낸다면 Duration 같은 자료형을 사용하거나, 그렇게 하기 어려운 상황이면 변수 이름에 밀리세컨드라는 의미를 담아주는 방식으로 표현력 있는 이름을 사용해주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +                .sign(Algorithm.HMAC256(secretKey));
`Algorithm.HMAC256(secretKey)` 인스턴스를 매번 생성할 필요가 있을까요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +    public boolean validateToken(String token) {
boolean 을 응답하는 경우 isValidToken 등의 이름이 더 잘 어울릴 것 같아요. 
validate 는 true/false 보다는 검증하고 어긋난 경우 exception 던지는 등의 동작의 이름으로 더 적절합니다.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +        return Long.parseLong(decodedJWT.getSubject());
33 라인에서 숫자를 파싱하는데 실패하면 애플리케이션이 어떻게 동작하나요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +        Date validity = new Date(now.getTime() + INFINITE_EXPIRATION);
validity 는 어떤 의미로 이름을 지어주신걸까요? 
27라인 `.withExpiresAt(` 메서드에서 사용하는 expiresAt 등의 이름이 유효기한을 나타내는데 적절해보이네요.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +    private final long INFINITE_EXPIRATION = 1000L * 60L * 60L * 24L * 365L * 100L; // 100년
intellij 에서 18라인에 warning 나오는데, 처리하지않고 그냥 두신 이유가 있을까요? 
의도하고 무시하는게 아니라면, warning 다 없애주세요. 
문법적으로 없앨 수 없는 경우거나, 의도한 경우이면 `@SupressWarnings` 애너테이션 사용해서 명시적으로 무시해주세요.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +    private final long INFINITE_EXPIRATION = 1000L * 60L * 60L * 24L * 365L * 100L; // 100년
상수로 빼서 사용하기 위함이라면 static 붙여주세요.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/LoginRequest.java
> +    private final String providerType;
다른 api 구현 참고해서 validation 추가해주세요. (`@NotNull`, `@NotEmpty` 등)

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
> +        /* TODO : Token 생성 */
이미 토큰 생성하는 로직 추가해주셨는데 이 주석 계속 필요한가요? 
불필요한 주석이면 제거해주세요.

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
> +        String token = jwtTokenProvider.generateToken(member.getMemberId());
컨트롤러에서 비즈니스 로직 작성하지 말아주세요. 
표현계층에서는 어떻게 보여지는지에 대한 관심사만 처리하는게 좋습니다. 
application service 로 옮겨주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/application/login/LoginApplicationService.java
> +        return memberService.join(
applicationService 는 login 이고 memberService 는 join 으로 명명하신 이유가 있을까요? 
memberService 는 정보가 있는 회원이면 그대로 리턴하고, 없으면 새로 만드는 로직인데 join 만으로는 동작을 표현하기 어려운거같아요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberService.java
> +    Member join(String authProviderType, String authProviderUserId);
메서드 시그니처를 parameter 2개를 각각 넘겨받도록 설계하신 이유가 있을까요? 
LoginRequestVo 도 똑같은 2개 parameter 를 갖고있어서 vo 하나만 넘겨받아도 될 것 같은데요. 
두 가지 방식이 어떤 차이가 있을까요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        if(member.isPresent()) {
포매팅 신경써주세요. (`if (`)
IDE 에서 저장/커밋 등 특정 이벤트마다 자동으로 저장하는 기능도 있으니 참고하세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProvider.java
> +@Setter
`setter` 는 왜 필요한가요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/Member.java
> +    @JsonManagedReference
몰라서 여쭤보는건데 `@JsonManagedReference`은 어떤 동작을 하나요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProviderStatus.java
> +    INACTIVE
탈퇴를 의미하는거라면 `WITHDRAWAL` 등으로 명확하게 이름 사용하면 좋을 것 같습니다. 
우선 떠오르는 휴면, 탈퇴 등의 2가지 상태 모두 INACTIVE 에 포함될 수 있어서 모호한 표현이네요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/Member.java
>  // TODO: 상태, 인증 제공자, 인증 제공자의 사용자 식별자, 권한, fcmToken
TODO 중 구현 된 내용이 있다면 주석도 수정해주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        String testName = "test";
test 로 두신건 의도하신건가요? 
익명로그인시 닉네임 정책은 어떻게되나요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProviderCreateVo.java
> +    Member member;
VO 에 엔티티 직접 담는건 지양해주세요. 
VO 가 항상 트랜잭션 범위 안에 있다고 보장하기 어려워서, 다음 트랜잭션 범위에 들어갔을 때 의도치않게 엔티티 상태가 바뀐채로 저장되는 등의 부작용이 발생할 수 있어서요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProvider.java
> +    public static AuthProvider from(AuthProviderCreateVo authProviderCreateVo) {
필드와 메서드 사이에 한줄 정도는 띄어주시는게 보기 편할거같아요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProvider.java
> +    private String authProviderType;
ANONYMOUS, KAKAO, APPLE 등이 들어가는 필드가 맞을까요? 
실수하기 좋은 String 보다는 컴파일 타임에 더 많은 정보를 가지고 있는 enum 을 사용하면 좋을 것 같습니다.

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        Member newMember = Member.from(MemberCreateVo.of(testName, MemberStatus.ACTIVE));
MemberCreateVo 를 통해서 member 를 생성할 때 ACTIVE 가 아닌 상태가 있나요? 
굳이 두번째 패러미터를 받아야할 이유가 있을까요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberUpdateVo.java
> +
불필요한 빈 라인 삭제해주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/SecurityConfig.java
>          // TODO: jwt 검증, 회원번호 조회
코드 변경에 따라 주석도 같이 업데이트 해주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberResponse.java
> +    private List<AuthProvider> authProviders;
외부에 응답 내보낼때는 도메인모델을 그냥 내보내지 말고, 적절한 dto 로 변경해서 응답해주세요.

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/Member.java
> +    @JoinColumn(name = "member_id")
우리 프로젝트에서 쓰고있는 ORM 에서 Naming Strategy 로 어떤 방식을 사용하고있는지 확인해보시면 좋을 것 같아요. 
다른 엔티티는 컬럼이름을 어떻게 쓰는지도 참고해보세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/SecurityConfig.java
>              Object principal = authentication.getPrincipal(); // accessToken
로직 구현 해주셨으니 뒤에 불필요해진 주석은 지워주세요

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/application/login/LoginRequestVo.java
> +    String providerType;
authProviderType, providerType 혼용해서 쓰는거같은데 이유가 있을까요?

2023-06-28 13:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        Optional<Member> member = memberRepository.findByAuthProviders_AuthProviderTypeAndAuthProviders_AuthProviderUserId(
이미 탈퇴한 멤버의 정보로 로그인을 시도한다면, 어떻게 동작할까요?

2023-06-28 14:41 UTC, seungwooKim99 commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +        Date now = new Date();
이건 인지하지 못하고 있었네요. 반영하겠습니다!

2023-06-28 14:46 UTC, seungwooKim99 commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +                .sign(Algorithm.HMAC256(secretKey));
인스턴스가 계속 생성되는걸 인지하지 못했네요. JwtTokenProvider의 변수로 선언해 반영하겠습니다 감사합니다.

2023-06-28 14:50 UTC, seungwooKim99 commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +        Date validity = new Date(now.getTime() + INFINITE_EXPIRATION);
토큰이 만료되지 않고 유효한 시간이라는 의미로 지었습니다. 지금 다시 보니 이름이 직관적이지 않네요. 리뷰해주신 대로 반영하겠습니다.

2023-06-28 15:03 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/application/login/LoginApplicationService.java
> +        return memberService.join(
로그인 구현하기 이전에 해성님이 남겨주신 레퍼런스 프로젝트를 살펴보며 네이밍을 참고했는데요, 그 과정에서 네이밍을 그대로 따랐던 것 같습니다. applicationService의 login에서 회원 유무를 확인하고, 없을 경우 예외로 memberService.join을 호출해서 회원가입을 진행하도록 수정해볼게요.

2023-06-28 15:11 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberService.java
> +    Member join(String authProviderType, String authProviderUserId);
돌이켜보니 일단 돌아가게라도 구현을 급하게 하다보니 이런 vo에 대한 정의가 미흡했던 것 같습니다. 시간을 갖고 코드를 다시 정리하고 QA가 필요했던 것 같네요... 다음 PR부터는 사소한 실수나 컨벤션에 어긋나는 코드는 먼저 정리한 후 올리도록 하겠습니다. 시간 써주셔서 너무 죄송하고 지적해주셔서 감사합니다.

2023-06-28 15:16 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProvider.java
> +@Setter
없어도 될 것 같습니다. AuthProvider와 Member의 트랜잭션을 확인하는 과정에서 잠시 넣었다가 빼는 데에 깜빡한 듯 합니다.

2023-06-28 15:22 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/Member.java
> +    @JsonManagedReference
@JsonManagedReference 로 순환참조를 방지할 수 있습니다. 그런데 이 어노테이션도 제거해야겠네요... OneToMany와 ManyToOne 으로 양방향 매핑되어있을 경우 무한하게 순환참조를 하게 되어 추가했습니다. 이후에 AuthProvider에 ManyToOne 어노테이션을 제거했기 때문에 불필요해졌습니다.

2023-06-28 15:26 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        String testName = "test";
아직 닉네임 정책을 고려하지 못해서 test로 두었습니다. 닉네임 정책과 구현은 task로 노션에 등록하겠습니다.

2023-06-28 15:34 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProvider.java
> +    private String authProviderType;
네 맞습니다. 그런데 저번 전체세션 때 잠깐 피드백 주셨던 내용을 authProviderType을 String으로 바꾸는 것이라 이해해서 String으로 처리했습니다. 혹시 저번에 주신 피드백 중 제가 잘못 이해하거나 놓치고 있던게 있을까요?

아래는 String으로 바꾸기 이전 Member 엔티티 일부입니다.
```java
public class Member {
    //...
    @Enumerated(EnumType.STRING)
    private MemberStatus status;

    private String authProviderUserId;
    
    @Enumerated(EnumType.STRING)
    private AuthProviderType authProviderType;
    //...
}
```

2023-06-28 15:36 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        Member newMember = Member.from(MemberCreateVo.of(testName, MemberStatus.ACTIVE));
MemberCreateVo에서는 불필요한 파라미터네요. 반드시 ACTIVE인 상태이므로 MemberCreateVo 내부에서 ACTIVE로 선언하겠습니다!

2023-06-28 15:41 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/application/login/LoginRequestVo.java
> +    String providerType;
오타입니다. 수정하겠습니다!

2023-06-28 15:43 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        Optional<Member> member = memberRepository.findByAuthProviders_AuthProviderTypeAndAuthProviders_AuthProviderUserId(
테스트를 해보진 않았지만 active한 회원처럼 정상 로그인이 될 것 같습니다. 탈퇴한 회원에 대한 예외처리를 신경쓰지 못했습니다. task로 등록해서 반영하겠습니다.

2023-06-28 16:28 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/AuthProvider.java
> +    private String authProviderType;
entity, vo 에서는 표현력있게 쓰고, dto 에서 외부 보여줄 때 String 쓰자는 의미였어요- 
place entity 에서 enum 쓰는 코드들 응답할 때 어떻게 쓰는지 참고하시면 좋을거같아요

2023-06-29 06:51 UTC, seungwooKim99 commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +        return Long.parseLong(decodedJWT.getSubject());
NumberFormatException이 발생하네요.. 무심코 반드시 Long이 담겨있을것이라 기대하고 파싱했는데 예외처리를 해야겠네요. 감사합니다

2023-06-30 03:40 UTC, junhaesung requested changes
로그인 로직 관련해서 코멘트 확인해주세요
다른 리팩토링 관련 코멘트는 필수는 아니니 천천히 반영해주세요

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/application/login/LoginApplicationService.java
> +        } catch (MemberNotFoundException e) {
나중에 얍 끝나고 기회되면 이펙티브 자바 책 읽으면서 리팩토링 해보시면 좋을거같아요 
> 아이템 69. 예외는 진짜 예외 상황에만 사용하라

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/application/login/LoginResponseVo.java
> +@Value(staticConstructor = "of")
사용하지 않는 메서드는 지워주세요 `(staticConstructor=of)`

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +    static int EXPIRATION_DURATION_IN_YEAR = 100;
외부에서 접근하지 않는걸로 보이는데요. 
접근지정자를 package-private 로 설정하신 이유가 있나요? 
별다른 이유가 없다면 private 으로 변경해주세요

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +                .withIssuedAt(java.sql.Timestamp.valueOf(now))
(이번에 말고, 8/5 이후에 적용해주세요.)

Date 를 쓰지 않기위해, Date 를 상속한 클래스를 사용하는건 문제를 해결하는 방법이 아닙니다. 
```
// java.sql.Timestamp.java
public class Timestamp extends java.util.Date {
...
```

아래 overloading 된 메서드 참고해서 더 나은방법으로 시간 값을 전달해보면 좋을거같아요

<img width="645" alt="image" src="https://github.com/YAPP-Github/coffice-server/assets/4813025/7d04da1d-9eb5-4932-a90a-e72eace2419f">

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/JwtTokenProvider.java
> +@RequiredArgsConstructor
이 생성자는 이제 필요없어보이네요. 
없어도 잘 동작한다면 제거해주세요

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/LoginAssembler.java
> +    public LoginResponse toLoginResponse(LoginResponseVo loginResponseVo) {
필드, 메서드 사이에는 한 줄 정도 띄어주시면 좋을거같아요.

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/LoginRequest.java
> +    @NotNull
빈 문자열이 의미가 없는 경우라면 `@NotBlank` 도 고려해보시면 좋을거같아요

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberAssembler.java
> +                        .map(it -> AuthProviderResponse.of(it))
IDE 에 표시되는 warning 확인하고 해결해주세요. 28라인도 동일합니다.

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
> +                        LoginRequestVo.of(
LoginRequest -> LoginRequestVo 변환 로직은 assembler 대신 여기서 직접 처리하는 이유가 있을까요?

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/test/resources/application.yml
> +    secret: secret
👍

2023-06-30 03:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        AuthProvider authProvider = AuthProvider.from(AuthProviderCreateVo.of(AuthProviderType.ANONYMOUS, authProviderUserId));
로그인 요청시 익명인지 여부를 클라이언트가 보내주는데요
생성시에는 이 parameter 를 전달받지 않고 익명인증으로 하드코딩하신 이유가 있을까요? 

예를들어, `{KAKAO, 1}` 이런 요청을 보냈는데 디비에 `{KAKAO, 1}` 필드가 없다면 `{ANONYMOUS, 1}` 멤버를 새로 만들어줄텐데요. 

맞게 동작하는건지 확인해보시고 개선해주세요.

2023-06-30 03:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        newMember.getAuthProviders().add(authProvider);
객체 생성시에는 되도록 완전한 상태로 한번에 만들어주세요. 
현재는 Member.from 으로 이름만 채워주고, 나중에 authProviders 에 직접 접근해서 element 추가하는데요. 
이런 방식은 객체지향에도 맞지 않고 다른 개발자들이 코드 수정시 실수할 여지가 많아서요.

2023-06-30 03:40 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/authProvider/AuthProvider.java
> +public class AuthProvider {
(이번에 말고, 8/5 이후에 봐주세요)

AuthProvider 와 AuthProviderVo 를 구분해서 설계하신 이유가 있을까요? 
`authProviderId` 식별자가 아무 의미를 못가지는 것 같아서요.

2023-06-30 03:40 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/SecurityConfig.java
>              Object principal = authentication.getPrincipal(); // accessToken
70 라인의 아래 주석도 지워주세요! 
```
// accessToken 
```

2023-06-30 04:20 UTC, seungwooKim99 commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
> +                        LoginRequestVo.of(
assembler 쓰는게 익숙치 않아서 놓치고 있었네요. 반영하겠습니다!

2023-06-30 04:23 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        AuthProvider authProvider = AuthProvider.from(AuthProviderCreateVo.of(AuthProviderType.ANONYMOUS, authProviderUserId));
첫 회원가입은 반드시 익명으로 진행되므로 하드코딩 했습니다. {KAKAO, 1} 과 같은 요청에 대한 예외처리는 아직 반영하지 못했습니다. 다음 PR에서 반영하도록 하겠습니다.

2023-06-30 07:30 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        newMember.getAuthProviders().add(authProvider);
Member와 authProvider 객체를 생성하는 과정에서 고민이 많았는데요. MemberCreateVo를 사용하며 객체를 생성하다보니  Vo에는 AuthProvider 도메인 객체를 넣을 수가 없어서 객체를 따로 생성했습니다.

조금 더 고민해보고 아래와 같이 Member.from 메서드를 수정해봤는데요. MemberCreateVo에 AuthProviderCreateVo를 추가했습니다. 그리고 Member.from 메서드에서 두 객체를 직접 생성합니다. 이렇게 구현하면 Member 객체가 완전한 상태로 생성되는 것일까요?
```java
public static Member from(MemberCreateVo memberCreateVo) {
        Member member = new Member();
        member.name = memberCreateVo.getName();
        member.status = MemberStatus.ACTIVE;
        member.authProviders.add(AuthProvider.from(memberCreateVo.getAuthProviderCreateVo()));
        return member;
    }
```

또는 Member 생성자에 AuthProvider 객체를 직접 주입해야 하는 것인지 고민이 됩니다..!!

2023-06-30 07:38 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/authProvider/AuthProvider.java
> +public class AuthProvider {
LoginResponse 객체를 만들 때 AuthProvider 정보를 Vo로 전달하기 위해 구분해서 설계했습니다..! AuthProviderInfoVo 와 같은 이름으로 바꿔야 할까요?

그리고 다시 생각해보니 AuthProviderId가 아무 의미를 가지지 않는다는 것에 동감합니다..! 사실 AuthProviderType과 AuthProviderUserId 두 필드가 식별자 역할을 하니 이 두 값을 composite key로 구성하는게 더 정규화가 잘 된것 같네요.

2023-06-30 08:21 UTC, junhaesung requested changes
login api validation 부분만 한 번 더 확인해주세요. 
테스트 어떻게 하셨는지도 남겨주세요

2023-06-30 08:21 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/infrastructure/spring/SecurityConfig.java
>              Object principal = authentication.getPrincipal(); // accessToken
요건 안지우신거같은데 중요한거 아니라 넘길게요

2023-06-30 08:21 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/authProvider/AuthProvider.java
> +public class AuthProvider {
authProviderType, authProviderUserId 처럼 lifecycle 이 거의 동일하고, 함께 사용되어야 (사용자 식별하는 기능으로서) 의미있는 경우는, 클래스로 묶어서 사용하시는 것도 좋아요. 

mysql 에서 복합키와 인조키를 어떻게 사용하는지는, 객체지향과 관계형 데이터베이스가 다르고, 정규화와 성능이 또 다른 주제라서 여기서 길게 언급 안할게요. 
결론만 말하면 mysql 은 성능문제로 복합키보다는 인조키 사용하는걸 선호합니다. 
이 코드에서는 엔티티가 아닌 클래스로 설계하고 `@ElementCollection` 등으로 사용하는 것도 방법이지 않을까 하는 제안이에요

2023-06-30 08:21 UTC, junhaesung commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
>              @RequestBody LoginRequest loginRequest
여기 `@Valid` 애너테이션 추가해야 LoginRequest 클래스에 추가한 validation 관련 애너테이션들이 동작해요. 
테스트 해보셨을까요? providerType 으로 enum 에 없는 값 입력하거나, 값이 비었거나 공백문자만 있는 등의 예외케이스일때도 400 대 에러 및 메시지 잘 나가는지 테스트해주세요

2023-06-30 15:17 UTC, seungwooKim99 commented on coffice-api/src/main/java/kr/co/yapp/_22nd/coffice/ui/member/MemberController.java
>              @RequestBody LoginRequest loginRequest
login 테스트 케이스 및 테스트 결과
- authProviderType, authProviderUserId 중 최소 하나가 null, "", " " 인 모든 경우의 수 -> 400 Error (기대값: 400 Error)
- authProviderType이 "ANONYMOUS", authProviderUserId가 비어있지 않은 문자열인 경우 -> 200 OK (기대값: 200 OK)
- authProviderType이 "KAKAO", "APPLE" 중 하나이고 authProviderUserId가 비어있지 않은 문자열인 경우
 -> 200 OK (기대값: 400 대 Error)
 
 마지막 케이스는 의도하지 않은 동작으로 이후 PR에서 예외처리가 필요합니다.

2023-06-30 19:13 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberServiceImpl.java
> +        newMember.getAuthProviders().add(authProvider);
member 클래스를 사용할 떄 되도록 불변으로 동작하게끔 로직 짜주시면 돼요. 
생성자에 parameter 가 몇개인지, 어떤 클래스를 넘겨주는지는 그 다음 고민인 것 같습니다. 

예시로 들어주신 코드도 가능할 것 같네요. 
이전 코드를 사용한다면, member.getAuthProviders().add(...) 처럼 내부 필드에 직접 접근해서 수정하기보다 member.addAuthProvider(...) 등으로 메서드 만들어서 추상화하고, 내부에서는 필요한 validation 하는 등으로 작성할 수 있을거같아요 

AuthProviderCreateVo 는 좀더 나은 이름을 붙이면 좋을거같아요. 
authProviderType, authProviderUserId 는 인증 정보 생성 뿐만 아니라 사용자 식별할 때도 같이 묶어서 쓰는 값인데, ~CreateVo 등으로 의미를 제한해버리면 다른 usecase 에서 사용할 수 없거나, 사용하면 어색한 상황이 되어서요. 
예를들면, AuthProviderKey 등으로 추상화해볼 수 있을 것 같네요

2023-06-30 19:15 UTC, junhaesung commented
고생하셨습니다- 

이후 PR 로 작업 나눈다고 말씀주신 부분들 노션에 추가 부탁드려요.

2023-06-30 19:15 UTC, junhaesung approved these changes

2023-06-30 19:34 UTC, merged