feat: 회원가입시 랜덤 이름 부여
YAPP-Github/22nd-iOS-Team-1-BE pull request #94
Opened 2023-07-03 16:26 UTC by seungwooKim99

이름 정책에 맞게 회원가입 유저에게 랜덤 이름을 부여합니다.

테스트
- 새로 회원가입시 랜덤한 이름 생성되는 것 확인

2023-07-03 16:34 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Noun.java
> +    카페전문가("카페전문가")
단일명사가 아니라 좀 애매하네요
{카피, 카페}, {애호가, 전문가} 각각 조합한걸로 보여서요 ㅋㅋ

2023-07-03 16:34 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Noun.java
> +    카페전문가("카페전문가")
한글로 코드 작성하는 것도 그렇고, enum 이름과 값을 중복으로 쓰는게 좀 어색한데요. 
네이밍 어려워서 이렇게 된거라면 차라리 테이블 만들어서 조회해서 쓰는건 어떠세요? 
enum 으로 관리하면 기획에서 단어 줄때마다 코드 바꾸고 배포까지 해야해서 번거로울거같기도해서요

2023-07-03 16:43 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Noun.java
> +    카페전문가("카페전문가")
단순하게 단어 리스트 한 번 받으면 안바뀔거라 기대해서... 조금 무식하게 짠거같네요ㅋㅋㅠ 말씀해주신대로 테이블로 만들어서 구현하는게 더 나을듯 합니다. 요건 오늘 오후중에 다시 개선해서 올려보겠습니다!

2023-07-04 17:12 UTC, junhaesung requested changes

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberRepository.java
> +    boolean existsByName(String name);
대소문자만 다른 문자열을 쿼리하면 mysql 에서 어떻게 동작할까요?

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Determiner.java
> +public class Determiner {
모든 테이블에 createdAt, updatedAt 추가해주세요. 
데이터를 추적하기 위해 '사실상 표준' 으로 사용하는 값입니다.

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Determiner.java
> +public class Determiner {
관형사라는 단어를 자주 안써서 찾아봤는데요, 우리 서비스에서의 활용을 보기엔 형용사가 더 적절해보여서요. 관형사로 부르는 이유가 궁금합니다.

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +        SecureRandom random = new SecureRandom();
ThreadLocalRandom 대신 SecureRandom 을 사용하신 이유가 있을까요? 두 클래스는 어떤 장단점이 있을까요?

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +    public String generateRandonName() {
오타 수정부탁드립니다

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +    private <T> T getRandomElement(SecureRandom random, List<T> list) {
빈 list 인 경우 예외처리 필요해보입니다.

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Noun.java
> +public class Noun {
여기도 동일하게 createdAt, updatedAt 추가해주세요

2023-07-04 17:12 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberCommandServiceImpl.java
> +            name = nameGenerationService.generateRandonName();
겹치는 이름을 발견할 때 마다, 형용사 명사 목록을 조회하는 쿼리가 발생하겠네요. 
나중에 개선해볼 수 있을거같아요.

2023-07-05 16:23 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberRepository.java
> +    boolean existsByName(String name);
구글링하며 알아본 결과 대소문자를 구분하지 않고 쿼리할 것 같습니다. 기대하는 동작은 대소문자를 구분하는 것인데요, 이 부분은 개선이 필요할 것 같습니다.

2023-07-05 16:33 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Determiner.java
> +public class Determiner {
말씀해주셔서 다시 검색해봤는데 "형용사" 또는 "수식어"가 더 적절할 듯 하네요. 처음에 관형사가 형용사보다 더 추상화된 개념이라 잘못 알고 있었습니다...

2023-07-05 16:37 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +        SecureRandom random = new SecureRandom();
ThreadLocalRandom을 사용했더니 SonarCloud에서 에러가 나타났습니다. 그래서 SonarCloud에서 알려준 방식대로 SecureRandom 으로 개선했습니다. 장단점은 아래와 같다고 합니다.

> Instances of ThreadLocalRandom are not cryptographically secure. Consider instead using [SecureRandom](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/SecureRandom.html) in security-sensitive applications

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ThreadLocalRandom.html

2023-07-06 00:46 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +        SecureRandom random = new SecureRandom();
네 장단점은 저도 리뷰하면서 검색해보았어요. 두 가지 클래스를 비교했을 때 SecureRandom 을 채택하신 근거를 여쭤보는거에요. 
정적분석 결과는 도움되는 자료를 제공하는거고, 의사결정은 엔지니어가 판단하는거예요. 
단순히 warning 만 보고 fix 한거라면 생각하시는 근거도 알려주세요.

2023-07-06 00:46 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/MemberRepository.java
> +    boolean existsByName(String name);
대소문자 구분 중요한 내용 아닌거같아요. 
이거 기획이랑 논의해서 스펙 바꾸는거 제안해보세요.

2023-07-06 01:24 UTC, seungwooKim99 commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +        SecureRandom random = new SecureRandom();
단순히 warning만 보고 고치긴 했습니다.. 기능 구현이 급해서 우선 추천해주는 방식대로 고쳤습니다. 단순히 워닝을 남길 이유가 없다고 생각했어요. 혹시 우려가 되는 부분이 있으실까요? 저는 크게 크리티컬 하지 않을것 같아서 깊게 고민하진 않았습니다. 만약 그런게 아니라면 짚어주시면 감사하겠습니다.

2023-07-08 08:30 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/Subject.java
> +public class Subject {
`@CreatedDate`, `@LastModifiedDate` 사용하려면 EntityListener 추가해주셔야해요. 다른 entity 참고해주세요

2023-07-08 08:37 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +    private final SubjectRepository nounRepository;
`nounRepository` 남아있는부분 이름 수정해주세요

2023-07-08 08:37 UTC, junhaesung commented on coffice-domain/src/main/java/kr/co/yapp/_22nd/coffice/domain/member/name/NameGenerationService.java
> +    private final ModifierRepository determinerRepository;
`determinerRepository` 도 바꿔주세요

2023-07-08 08:38 UTC, junhaesung approved these changes

2023-07-08 08:59 UTC, merged